@startuml

'default
left to right direction
actor Employee
rectangle Database

rectangle "Population Statistics System" {

    usecase UC1 as "Get capital cities"
    usecase UC2 as "Get cities"
    usecase UC3 as "Get countries"
    usecase UC4 as "Get countries languages"
    usecase UC5 as "Get the population of countries, cities and continents"


    Employee --> UC1
    UC1 -- Database
    Employee --> UC2
    UC2 -- Database
    Employee --> UC3
    UC3 -- Database
    Employee --> UC4
    UC4 -- Database
    Employee --> UC5
    UC5 -- Database

}
@enduml